import { useState, useEffect } from 'react';
import {
    SimpleGrid,
    Input,
    Select,
    Stack,
    Heading,
    Container,
    Text,
    Center,
} from '@chakra-ui/react';
import ExchangeCard from './ExchangeCard';
import { Exchange } from '../types/exchange';
import { fetchExchanges } from '../services/api';

interface ExchangeListProps {
    type: 'CEX' | 'DEX';
    title: string;
}

export default function ExchangeList({ type, title }: ExchangeListProps) {
    const [exchanges, setExchanges] = useState<Exchange[]>([]);
    const [loading, setLoading] = useState(true);
    const [search, setSearch] = useState('');
    const [sortBy, setSortBy] = useState('rank');

    useEffect(() => {
        const getData = async () => {
            setLoading(true);
            const data = await fetchExchanges(type);
            setExchanges(data);
            setLoading(false);
        };
        getData();
    }, [type]);

    const filteredExchanges = exchanges
        .filter((e) => e.exchange_name.toLowerCase().includes(search.toLowerCase()))
        .sort((a, b) => {
            if (sortBy === 'name') return a.exchange_name.localeCompare(b.exchange_name);
            if (sortBy === 'rank') {
                return parseInt(a.exchange_rank) - parseInt(b.exchange_rank);
            }
            if (sortBy === 'score') {
                const scoreA = parseFloat(a.exchange_trustscore || '0');
                const scoreB = parseFloat(b.exchange_trustscore || '0');
                return scoreB - scoreA;
            }
            return 0;
        });

    return (
        <Container maxW={'7xl'} py={12}>
            <Stack spacing={4} as={Container} maxW={'3xl'} textAlign={'center'} mb={12}>
                <Heading fontSize={'3xl'}>{title}</Heading>
                <Text color={'gray.600'} fontSize={'xl'}>
                    Ranked snapshot of top {type} exchanges generated by AI Studio.
                </Text>
            </Stack>

            <Stack direction={{ base: 'column', md: 'row' }} spacing={4} mb={8} justify="center">
                <Input
                    placeholder="Search exchanges..."
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    maxW={{ md: '300px' }}
                    variant="filled"
                />
                <Select
                    value={sortBy}
                    onChange={(e) => setSortBy(e.target.value)}
                    maxW={{ md: '200px' }}
                    variant="filled">
                    <option value="rank">Sort by Rank</option>
                    <option value="name">Sort by Name</option>
                    <option value="score">Sort by Trust Score</option>
                </Select>
            </Stack>

            <SimpleGrid columns={{ base: 1, md: 2, lg: 3 }} spacing={10}>
                {loading
                    ? Array(6)
                        .fill(0)
                        .map((_, i) => <ExchangeCard key={i} isLoading={true} />)
                    : filteredExchanges.map((exchange) => (
                        <ExchangeCard key={exchange.id} exchange={exchange} />
                    ))}
            </SimpleGrid>

            {(!loading && filteredExchanges.length === 0) && (
                <Center py={10}>
                    <Text fontSize="lg" color="gray.500">No {type} exchanges found matching your search.</Text>
                </Center>
            )}
        </Container>
    );
}
